### ISSUE TITLE
help

### ISSUE THREAD

**Issue by Vladi17** [analyzehim/instagram_photo_downloader#3]
hello! не получается запустить локально(
ругается на:
 except Exception, e
заменил на:
 except Exception as e

запускаю, в итоге: 
![hrh46y](https://user-images.githubusercontent.com/35336204/34971678-e56f7676-fa9d-11e7-8f1c-187ec83d2ca6.JPG)

в чем может быть проблема?
первый раз использую pyton

Python 3.6.4

**Comment by analyzehim** [comment]
Привет!

> первый раз использую pyton
Python 3.6.4

В этом и проблема, бот написан на python 2.7.
Версии питона не обладают обратной совместимостью.

**Comment by Vladi17** [comment]
поставил python 2.7.
вроде заработало, ссылку отправляю фотки сохраняются в папку,
а вот сообщение с картинкой не приходит почему то, хотя в консольке пишет мол отправлено.
Tue Jan 16 20:47:04 2018 >> images\BeAnV8LlpfW.jpg file is new

Tue Jan 16 20:47:04 2018 >> Sending photo to 225646622: images\BeAnV8LlpfW.jpg
в чем дело может быть?

**Comment by analyzehim** [comment]
Попробуй свежий фикс в `427e8a4213bf736e139b9e6e952c3d6efc5bc7f6`.
Скорее всего, проблема была со специфичной манерой windows прописывать пути до файлов.
